//! Custom FileLoader that injects generated Rust stubs as a virtual file.
//!
//! The consumer's types and functions must be visible to rustc as Rust source code
//! (struct definitions + extern declarations). Instead of writing a real .rs file
//! to disk, we intercept rustc's file reading: when rustc tries to load
//! `__lang_stubs.rs`, we return the consumer's generated stub source.
//!
//! The consumer's test/app .rs files use `mod __lang_stubs; use __lang_stubs::*;`
//! to pull in the generated definitions. Rustc parses them normally, assigns DefIds,
//! runs type checking — and then our query overrides intercept layout/MIR/borrowck
//! queries for those items.
//!
//! The stubs are generated by the consumer's `generate_stubs()` callback (Phase 1,
//! before rustc starts). The FileLoader is installed in `LangDriver::config()`.

use rustc_data_structures::sync::Lrc;
use rustc_span::source_map::{FileLoader, RealFileLoader};
use std::io;
use std::path::Path;

/// Wraps `RealFileLoader` to intercept reads of `__lang_stubs.rs` and return
/// the consumer's generated stub source instead of reading from disk.
///
/// For all other files, delegates to `RealFileLoader` (normal file I/O).
pub struct LangFileLoader {
    inner: RealFileLoader,
    stubs: String,
}

impl LangFileLoader {
    pub fn new(stubs: String) -> Self {
        Self { inner: RealFileLoader, stubs }
    }
}

impl FileLoader for LangFileLoader {
    fn file_exists(&self, path: &Path) -> bool {
        if is_stubs_path(path) { return true; }
        self.inner.file_exists(path)
    }

    fn read_file(&self, path: &Path) -> io::Result<String> {
        if is_stubs_path(path) { return Ok(self.stubs.clone()); }
        self.inner.read_file(path)
    }

    fn read_binary_file(&self, path: &Path) -> io::Result<Lrc<[u8]>> {
        if is_stubs_path(path) {
            return Ok(Lrc::from(self.stubs.as_bytes()));
        }
        self.inner.read_binary_file(path)
    }
}

fn is_stubs_path(path: &Path) -> bool {
    path.file_name().map_or(false, |n| n == "__lang_stubs.rs")
}
